import Head from 'next/head'
import Link from 'next/link';
import styles from '../../styles/CharacterDetails.module.css'

export const getServerSideProps = async (context) => {
  const { id } = context.query
  const res = await fetch(`https://rickandmortyapi.com/api/character/${id}`)
  const detail = await res.json()
  return {
    props: {
      detail,
    }
  }
}

const CharacterDetails = ({ detail }) => {
  return (
    <div className={styles.detailContainer}>
      <Head>
        <title>Rick and Morty | Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"></link>
      </Head>
      <h1 className='text-center display-4 m-4 '>{detail.name}</h1>
      <div class="card" style={{ maxWidth: "18rem" }}>
        <img class="card-img-top" src={detail.image} alt="Card image cap" />
        <div class="card-body">
          <h4>Name: {detail.name}</h4>
          <p class="card-text">
            Status: {detail.status} <br />
            Gender: {detail.gender} <br />
            Species: {detail.species} <br />
            Location: {detail.location?.name} <br />
            Originally From: {detail.origin?.name}
          </p>
        </div>
          <Link href="/">
            <button className="btn btn-primary">Go Back Home</button>
          </Link>
      </div>
    </div>
  )
}

export default CharacterDetails
