import Head from 'next/head'
import { useState } from 'react'
import Episode from '../components/Episode'
import styles from '../styles/Episode.module.css'

export const getStaticProps = async () => {
  const res = await fetch('https://rickandmortyapi.com/api/episode')
  const data = await res.json()
  return {
    props: {
      data
    }
  }
}

export default function Episodes({ data }) {
  const { info, results: defaultResults = [] } = data;
  const [results, updateResults] = useState(defaultResults);
console.log(results)
  return (
    <div className={styles.episodesContainer}>
      <Head>
        <title>Rick and Morty | Episodes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"></link>
      </Head>
        <Episode results={results}/>
    </div>
  )
}


