import Head from 'next/head'
import { useState } from 'react'
import Episode from '../components/Episode'
import styles from '../styles/Home.module.css'


export const getStaticProps = async () => {
  const res = await fetch('https://rickandmortyapi.com/api/episode')
  const data = await res.json()
  return {
    props: {
      data
    }
  }
}

export default function Episodes({ data }) {
  const { info, results: defaultResults = [] } = data;
  const [results, updateResults] = useState(defaultResults);
console.log(results)
  return (
    <div className={styles.homeContainer}>
      <Head>
        <title>Rick and Morty | Episodes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Episode results={results}/>
    </div>
  )
}


