import Head from 'next/head'
import { useEffect, useState } from 'react'
import Cards from '../components/Cards'
import Pagination from '../components/Pagination';
import styles from '../styles/Home.module.css'


export default function Home() {
  const [results, setResults] = useState([]);
  const [info, setInfo] = useState({});

  const API_URL = "https://rickandmortyapi.com/api/character";

  const fetchCharacters = (API_URL) => {
    fetch(API_URL)
      .then((res) => res.json())
      .then((data) => {
        setResults(data.results);
        setInfo(data.info);
      })
      .catch((err) => console.log(err));
  };


  const goToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  };

  const onPrevious = () => {
    fetchCharacters(info.prev);
    goToTop();
  };

  const onNext = () => {
    fetchCharacters(info.next);
    goToTop();
  };

  useEffect(() => {
    fetchCharacters(API_URL);
  }, []);


  return (
    <div className={styles.homeContainer}>
      <Head>
        <title>Rick and Morty | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cards results={results} />
      <Pagination
          prev={info.prev}
          onPrevious={onPrevious}
          next={info.next}
          onNext={onNext}
        />
    </div>
  )
}


