import Head from 'next/head'
import { useEffect, useState } from 'react'
import Cards from '../components/Cards'
import Pagination from '../components/Pagination';
import styles from '../styles/Home.module.css'
import Image from "next/image"
import bannerImg from '../public/banner.webp'


export default function Home() {
  const [results, setResults] = useState([]);
  const [info, setInfo] = useState({});

  const API_URL = "https://rickandmortyapi.com/api/character";

  const fetchCharacters = (API_URL) => {
    fetch(API_URL)
      .then((res) => res.json())
      .then((data) => {
        setResults(data.results);
        setInfo(data.info);
      })
      .catch((err) => console.log(err));
  };


  const goToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  };

  const onPrevious = () => {
    fetchCharacters(info.prev);
    goToTop();
  };

  const onNext = () => {
    fetchCharacters(info.next);
    goToTop();
  };

  useEffect(() => {
    fetchCharacters(API_URL);
  }, []);


  return (
    <div className={styles.homeContainer}>
      <Head>
        <title>Rick and Morty | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"></link>
      </Head>
      <div>
        <h1 className='text-center display-4 text-orange fw-bolder'>Rick and Morty</h1>
        <div className="row row-cols-1 row-cols-sm-1 row-cols-md-1 row-cols-lg-2 my-5 ">
          <Image src={bannerImg} alt="Rick-and-Morty" className={styles.homeImage}/>
          <div className="mt-5 fs-4">
            <p className={styles.homeText}>Rick and Morty is an American adult animated science fiction sitcom created by Justin Roiland and Dan Harmon for Cartoon Network's nighttime programming block, Adult Swim.</p>
            <p className={styles.homeText}>
              The series follows the misadventures of cynical mad scientist Rick Sanchez and his good-hearted, but fretful grandson Morty Smith, who split their time between domestic life and interdimensional adventures.
            </p>
          </div>
        </div>
      </div>
      <Cards results={results} />
      <Pagination
        prev={info.prev}
        onPrevious={onPrevious}
        next={info.next}
        onNext={onNext}
      />
    </div>
  )
}


