import Head from 'next/head'
import { useState } from 'react'
import Cards from '../components/Cards'
import styles from '../styles/Home.module.css'



export const getStaticProps = async () => {
  const res = await fetch('https://rickandmortyapi.com/api/character')
  const data = await res.json()
  return {
    props: {
      data
    }
  }
}

export default function Home({ data }) {
  const { info, results: defaultResults = [] } = data;
  const [results, updateResults] = useState(defaultResults);

  return (
    <div className={styles.homeContainer}>
      <Head>
        <title>Rick and Morty | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cards results={results}/>
    </div>
  )
}


